# Generated by Django 4.2.4 on 2024-02-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_caruser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caruser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user/media/uploads/'),
        ),
    ]
