# Generated by Django 4.2.4 on 2024-02-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=200)),
                ('last_name', models.CharField(default=None, max_length=200)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('phone_number', models.IntegerField(default=None)),
                ('instrument_type', models.CharField(default=None, max_length=200)),
            ],
        ),
    ]
